<div class="page-content">
    <h1 id="introduction">INTRODUCTION</h1>
    <div class="text-justify mb-4">
        <p>This Model Report is provided in template format to allow an approved RAW to process & record the full compliance requirements for a <b>SEV</b> vehicle & for an approved AVV to fully verify the process according to the requirements of the Road Vehicle Standards (Model Reports) Determination 2021 which operates under the authority of section 88 of the Road Vehicle Standards Rules 2019.</p>
        <p>This Model Report document has been created in-line with the requirements of the various Road Vehicles Standards Determinations 2021 (Model Reports / Model Reports - Compliance with Standards / Limit of Acceptable Damage or Corrosion / Verification of Road Vehicles) which apply for legal reasons.</p>
        <p>Each individual Model Report is printed from an online electronic system which has strict control protocols in place. QR codes & Watermarks are placed on each page for security purposes. The report should be printed in <b>colour</b> & in landscape format for clarity & security.</p>
        <p>It is recommended that both the RAW & the AVV independently work through the same Model Report (SEV) copy from the start to the finish following all instructions & filling in all the appropriate blanks as they apply. The VEHICLE SCOPE (Pre-modification Specifications) section must be completed & approved prior to starting the Work Instruction section as a rejection at this point means the report cannot proceed & The Department must be notified formally of the rejection details.</p>
        <p>Selection boxes & instructions are given through-out the report to assist with the vehicle checking process. The RAW must complete all check boxes as appropriate. These check boxes should always be “Yes” as any problems that arise must be rectified prior to the AVV carrying out their inspection.</p>
        <p>The AVV follows a similar procedure but the check boxes are reduced as they summarily review each document as marked & presented. The AVV is also responsible to upload photos & videos when directed throughout the Model Report. This also includes uploading copies of the noise level report, export certificate & other related evidence. It is important that the AVV receives a colored copy in landscape format of this Model Report so clear photographs are available for viewing. The AVV is responsible to scan the completed Model Report & submit to the Department for entry onto the RAV system with a copy also be given to the RAW.</p>
        <p>It is recommended that the RAW & AVV use the same Model Report document because it has been setup to be an actual working document guiding both parties through the vehicle checks, the modification process & the important verification process.</p>
    </div>
</div>
